import { ArrowUpRight, ChevronDown, Network, Sparkles } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { fetchApi } from '../../api/client';
import type { ObservatoryNode } from '../observatory/types';
import type { ArchitectureGraphResponse, ClusterInterpretationResponse } from './graphTypes';
import { architectureGraphScope } from './graphAdapter';

export default function ArchitectureGraphInspector({ node, onEnter, onExpand, scopeGroupId }: { node: ObservatoryNode | null; onEnter: (node: ObservatoryNode) => void; onExpand: (node: ObservatoryNode) => void; scopeGroupId?: string | null }) {
  const [graph, setGraph] = useState<ArchitectureGraphResponse | null>(null);
  const [interpretation, setInterpretation] = useState<ClusterInterpretationResponse | null>(null);
  const [interpreting, setInterpreting] = useState(false);
  useEffect(() => { void fetchApi<ArchitectureGraphResponse>('/architecture-graph').then(setGraph).catch(() => setGraph(null)); }, []);
  const scoped = useMemo(() => graph ? architectureGraphScope(graph, scopeGroupId) : null, [graph, scopeGroupId]);
  const selected = useMemo(() => scoped?.groups.find((group) => group.id === node?.id) ?? null, [scoped, node?.id]);
  const incoming = useMemo(() => selected ? (scoped?.aggregate_edges.filter((edge) => edge.target_group_id === selected.id) ?? []) : [], [scoped, selected]);
  const outgoing = useMemo(() => selected ? (scoped?.aggregate_edges.filter((edge) => edge.source_group_id === selected.id) ?? []) : [], [scoped, selected]);
  const internal = useMemo(() => selected ? (scoped?.internal_relation_counts.filter((value) => value.group_id === selected.id) ?? []) : [], [scoped, selected]);
  useEffect(() => { setInterpretation(null); setInterpreting(false); }, [selected?.id]);
  const generateInterpretation = async () => { if (!selected) return; setInterpreting(true); try { setInterpretation(await fetchApi<ClusterInterpretationResponse>(`/architecture-graph/clusters/${encodeURIComponent(selected.id)}/interpretation`, { method: 'POST' })); } catch { setInterpretation({ analysis_run_id: selected.analysis_run_id, cluster_id: selected.id, status: 'unavailable' }); } finally { setInterpreting(false); } };
  if (!scoped) return <aside className="architecture-graph-inspector" aria-label="Architecture graph inspector" />;
  if (!selected || !node) return <aside className="architecture-graph-inspector" aria-label="Architecture graph inspector"><p className="architecture-graph-inspector__eyebrow">Architecture overview</p><h2>{scoped.groups.filter((group) => !group.parent_group_id).reduce((count, group) => count + group.recursive_module_count, 0)} modules</h2><dl><div><dt>Regions</dt><dd>{scoped.groups.filter((group) => !group.parent_group_id).length}</dd></div><div><dt>Aggregate relations</dt><dd>{scoped.aggregate_edges.length}</dd></div></dl><p className="architecture-graph-inspector__copy"><Network size={15} /> Resolved calls, inheritance, and future imports are shown only when recovered deterministically.</p><p className="architecture-graph-inspector__hint">Select a structural region to inspect its relations.</p></aside>;
  const children = scoped.groups.filter((group) => group.parent_group_id === selected.id).length;
  if (selected.kind === 'relation_cluster') return <aside className="architecture-graph-inspector" aria-label="Selected deterministic relation cluster"><p className="architecture-graph-inspector__eyebrow">Relation cluster</p><h2>{interpretation?.interpretation?.label ?? selected.label}</h2>{interpretation?.interpretation && <p className="architecture-graph-inspector__ai-badge"><Sparkles size={13} /> AI interpretation</p>}<p className="architecture-graph-inspector__copy">{interpretation?.interpretation?.description ?? 'Derived mechanically from resolved source relationships.'}</p>{interpretation?.status === 'unavailable' && <p className="architecture-graph-inspector__copy">AI interpretation unavailable. Deterministic architecture remains available.</p>}{!interpretation && <button type="button" onClick={() => void generateInterpretation()} disabled={interpreting}>{interpreting ? 'Generating…' : 'Generate interpretation'}</button>}<p className="architecture-graph-inspector__deterministic">Deterministic identity · {selected.label}</p><dl><div><dt>Members</dt><dd>{selected.recursive_module_count}</dd></div><div><dt>Internal relations</dt><dd>{selected.internal_relation_count ?? 0}</dd></div><div><dt>Boundary relations</dt><dd>{selected.boundary_relation_count ?? 0}</dd></div><div><dt>Containing region</dt><dd>{selected.structural_path}</dd></div></dl><section><h3>Relation kinds</h3>{(selected.internal_relation_kind_counts ?? []).map(([kind, count]) => <p key={kind}>Internal {kind} · {count}</p>)}{(selected.boundary_relation_kind_counts ?? []).map(([kind, count]) => <p key={kind}>Boundary {kind} · {count}</p>)}</section><div className="architecture-graph-inspector__actions"><button type="button" onClick={() => onExpand(node)}><ChevronDown size={15} /> Expand</button></div></aside>;
  if (selected.kind === 'relation_residual') return <aside className="architecture-graph-inspector" aria-label="Selected residual group"><p className="architecture-graph-inspector__eyebrow">Residual group</p><h2>{selected.label}</h2><p className="architecture-graph-inspector__copy">These modules were not placed in a deterministic relation cluster from the currently recovered resolved relationships.</p><dl><div><dt>Modules</dt><dd>{selected.recursive_module_count}</dd></div></dl></aside>;
  return <aside className="architecture-graph-inspector" aria-label="Selected architecture region"><p className="architecture-graph-inspector__eyebrow">Structural region</p><h2>{node.label}</h2><p className="architecture-graph-inspector__path">{selected.structural_path}</p><dl><div><dt>Modules</dt><dd>{selected.recursive_module_count}</dd></div><div><dt>Child groups</dt><dd>{children}</dd></div></dl>{internal.length > 0 && <section><h3>Internal relations</h3>{internal.map((value) => <p key={value.relation_kind}>{value.relation_kind} · {value.member_relation_count}</p>)}</section>}<section><h3>Boundary relations</h3><p>{outgoing.length} outgoing · {incoming.length} incoming</p>{[...outgoing, ...incoming].slice(0, 5).map((edge) => <p key={edge.id}>{edge.relation_kind} · {edge.member_relation_count}</p>)}</section><div className="architecture-graph-inspector__actions"><button type="button" onClick={() => onExpand(node)}><ChevronDown size={15} /> Expand</button><button type="button" onClick={() => onEnter(node)}><ArrowUpRight size={15} /> Enter</button></div></aside>;
}
