import { ArrowUpRight, ChevronDown, Network, Sparkles } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { fetchApi } from '../../api/client';
import type { ObservatoryNode } from '../observatory/types';
import type { ArchitectureGraphResponse, ClusterInterpretationResponse } from './graphTypes';
import { architectureGraphScope } from './graphAdapter';

export default function ArchitectureGraphInspector({ node, onEnter, onExpand, scopeGroupId }: { node: ObservatoryNode | null; onEnter: (node: ObservatoryNode) => void; onExpand: (node: ObservatoryNode) => void; scopeGroupId?: string | null }) {
  const [graph, setGraph] = useState<ArchitectureGraphResponse | null>(null);
  const [interpretation, setInterpretation] = useState<ClusterInterpretationResponse | null>(null);
  const [interpreting, setInterpreting] = useState(false);
  useEffect(() => { void fetchApi<ArchitectureGraphResponse>('/architecture-graph').then(setGraph).catch(() => setGraph(null)); }, []);
  const scoped = useMemo(() => graph ? architectureGraphScope(graph, scopeGroupId) : null, [graph, scopeGroupId]);
  const selected = useMemo(() => scoped?.groups.find((group) => group.id === node?.id) ?? null, [scoped, node?.id]);
  const incoming = useMemo(() => selected ? (scoped?.aggregate_edges.filter((edge) => edge.target_group_id === selected.id) ?? []) : [], [scoped, selected]);
  const outgoing = useMemo(() => selected ? (scoped?.aggregate_edges.filter((edge) => edge.source_group_id === selected.id) ?? []) : [], [scoped, selected]);
  const internal = useMemo(() => selected ? (scoped?.internal_relation_counts.filter((value) => value.group_id === selected.id) ?? []) : [], [scoped, selected]);
  useEffect(() => { setInterpretation(null); setInterpreting(false); }, [selected?.id]);
  const generateInterpretation = async () => { if (!selected) return; setInterpreting(true); try { setInterpretation(await fetchApi<ClusterInterpretationResponse>(`/architecture-graph/clusters/${encodeURIComponent(selected.id)}/interpretation`, { method: 'POST' })); } catch { setInterpretation({ analysis_run_id: selected.analysis_run_id, cluster_id: selected.id, status: 'unavailable' }); } finally { setInterpreting(false); } };
  if (!scoped) return <aside className="architecture-graph-inspector" aria-label="Architecture graph inspector" />;
  if (!selected || !node) return <aside className="architecture-graph-inspector" aria-label="Architecture graph inspector"><p className="architecture-graph-inspector__eyebrow">Architecture overview</p><h2>Architecture Overview</h2><p className="architecture-graph-inspector__copy">Choose a structural region to see recovered relationships, clusters, and modules.</p><dl><div><dt>Modules</dt><dd>{scoped.groups.filter((group) => !group.parent_group_id).reduce((count, group) => count + group.recursive_module_count, 0)}</dd></div><div><dt>Regions</dt><dd>{scoped.groups.filter((group) => !group.parent_group_id).length}</dd></div><div><dt>Relations</dt><dd>{scoped.aggregate_edges.length}</dd></div></dl><p className="architecture-graph-inspector__hint"><Network size={15} /> Only relationships recovered from source are shown.</p></aside>;
  const children = scoped.groups.filter((group) => group.parent_group_id === selected.id).length;
  if (selected.kind === 'relation_cluster') return <aside className="architecture-graph-inspector" aria-label="Selected deterministic relation cluster">
    <p className="architecture-graph-inspector__eyebrow">Relation cluster</p>
    {interpretation?.interpretation ? <><h2>{interpretation.interpretation.label}</h2><p className="architecture-graph-inspector__ai-badge"><Sparkles size={13} /> AI interpretation <span>Optional, not verified</span></p><p className="architecture-graph-inspector__copy">{interpretation.interpretation.description}</p><div className="architecture-graph-inspector__basis"><p className="architecture-graph-inspector__section-label">Deterministic basis</p><strong>{selected.label}</strong><span className="architecture-graph-inspector__technical-label">Deterministic identity · {selected.label}</span></div></> : <><h2>{selected.label}</h2><p className="architecture-graph-inspector__copy">Derived from recovered source relationships.</p><p className="architecture-graph-inspector__technical-label">Derived mechanically from resolved source relationships.</p><button type="button" onClick={() => void generateInterpretation()} disabled={interpreting}>{interpreting ? 'Generating...' : 'Generate interpretation'}</button>{interpretation?.status === 'unavailable' && <p className="architecture-graph-inspector__copy architecture-graph-inspector__copy--muted">AI interpretation is unavailable. Deterministic architecture data remains available.</p>}</>}
    <dl><div><dt>Modules</dt><dd>{selected.recursive_module_count}</dd></div><div><dt>Internal calls</dt><dd>{selected.internal_relation_count ?? 0}</dd></div><div><dt>Boundary calls</dt><dd>{selected.boundary_relation_count ?? 0}</dd></div><div><dt>Containing region</dt><dd>{selected.structural_path}</dd></div></dl>
    <section><h3>Relation kinds</h3><p><span>Internal relations</span><span> · {selected.internal_relation_count ?? 0}</span></p>{(selected.internal_relation_kind_counts ?? []).map(([kind, count]) => <p key={kind}>Internal {kind} · {count}</p>)}{(selected.boundary_relation_kind_counts ?? []).map(([kind, count]) => <p key={kind}>Boundary {kind} · {count}</p>)}</section>
    <div className="architecture-graph-inspector__actions"><button type="button" onClick={() => onExpand(node)}><ChevronDown size={15} /> Expand cluster</button></div>
  </aside>;
  if (selected.kind === 'relation_residual') return <aside className="architecture-graph-inspector" aria-label="Selected residual group"><p className="architecture-graph-inspector__eyebrow">Unclustered modules</p><h2>{selected.label}</h2><p className="architecture-graph-inspector__copy">No useful relation cluster was recovered for these modules from the currently available source relationships.</p><dl><div><dt>Modules</dt><dd>{selected.recursive_module_count}</dd></div></dl></aside>;
  return <aside className="architecture-graph-inspector" aria-label="Selected architecture region"><p className="architecture-graph-inspector__eyebrow">Structural region</p><h2>{node.label}</h2><p className="architecture-graph-inspector__path">{selected.structural_path}</p><dl><div><dt>Modules</dt><dd>{selected.recursive_module_count}</dd></div><div><dt>Child groups</dt><dd>{children}</dd></div></dl>{internal.length > 0 && <section><h3>Internal relations</h3>{internal.map((value) => <p key={value.relation_kind}>{value.relation_kind} · {value.member_relation_count}</p>)}</section>}<section><h3>Boundary relations</h3><p>{outgoing.length} outgoing · {incoming.length} incoming</p>{[...outgoing, ...incoming].slice(0, 5).map((edge) => <p key={edge.id}>{edge.relation_kind} · {edge.member_relation_count}</p>)}</section><div className="architecture-graph-inspector__actions"><button type="button" onClick={() => onExpand(node)}><ChevronDown size={15} /> Expand</button><button type="button" onClick={() => onEnter(node)}><ArrowUpRight size={15} /> Enter</button></div></aside>;
}
